import documents2 from '@/data/documents2'
import aristotle from '@/assets/img/aristotle.jpg'
import cicero from '@/assets/img/cicero.jpg'
import marcoAurelio from '@/assets/img/marcoAurelio.jpg'
import mirceaEliade from '@/assets/img/mirceaEliade.jpg'
import mirceaEliade2 from '@/assets/img/mirceaEliade2.jpg'
import plato from '@/assets/img/plato.jpg'
import seneca from '@/assets/img/seneca.jpg'
import machado from '@/assets/img/machado.jpg'
import thomasMann from '@/assets/img/thomasMann.jpg'
import ecaQueiroz from '@/assets/img/ecaQueiroz.jpg'
import fernandoPessoa from '@/assets/img/fernandoPessoa.jpg'
import fernandoPessoa2 from '@/assets/img/fernandoPessoa2.jpg'
import monteiroLobato from '@/assets/img/monteiroLobato.jpg'
import kafka from '@/assets/img/kafka.jpg'
import kafka2 from '@/assets/img/kafka2.jpg'
import brunoTolentino from '@/assets/img/brunoTolentino.jpg'
import machado2 from '@/assets/img/machado2.jpg'
import machado3 from '@/assets/img/machado3.jpg'
import augustoAnjos from '@/assets/img/augustoAnjos.jpg'
import oscarWilde from '@/assets/img/oscarWilde.jpg'
import shakespeare from '@/assets/img/shakespeare.jpg'
import macbeth1 from '@/assets/img/macbeth1.jpg'
import macbeth2 from '@/assets/img/macbeth2.jpg'
import macbeth3 from '@/assets/img/macbeth3.jpg'
import macbeth4 from '@/assets/img/macbeth4.jpg'

export default {
  documents2,
  imgs: [aristotle, cicero, marcoAurelio, mirceaEliade, mirceaEliade2, plato, seneca, machado, thomasMann, ecaQueiroz, fernandoPessoa, fernandoPessoa2, monteiroLobato, kafka, kafka2, brunoTolentino, machado2, machado3, augustoAnjos, oscarWilde, shakespeare, macbeth1, macbeth2, macbeth3, macbeth4]
}
